### ISSUE TITLE
The CI failed

### ISSUE THREAD

**Issue by fonsp** [fonsp/PlutoUtils.jl#22]

**Comment by lungben** [comment]
The problem is that the credentials for uploading the Pluto Docker images to Dockerhub are not yet configured, see #20 .

**Comment by fonsp** [comment]
I did it, and re-ran the CI but it still failed :(

![image](https://user-images.githubusercontent.com/6933510/95122793-4f5a5e80-0751-11eb-9f57-d7e38c918e27.png)

**Comment by lungben** [comment]
@shashankp could you please help @fonsp here?
Unfortunately, I do not have hands-on experience in coupling Github Actions with Dockerhub.

**Comment by fonsp** [comment]
We got it!
