### ISSUE TITLE
Pluto to HTML without a browser

### ISSUE THREAD

**Issue by fonsp** [fonsp/PlutoUtils.jl#8]
Not too difficult, just some Julia code that produces roughly the same HTML as the JS code (have a look at the .html export). You can use https://github.com/yurivish/Hyperscript.jl or just `Markdown.withtag` to write it

**Comment by fonsp** [comment]
@shashi

**Comment by fredrikekre** [comment]
It would be great if this export function also supported only exporting the `main` part of the document, that would make it easy to include in a full HTML page with e.g. Franklin.jl.

**Comment by fonsp** [comment]
@shashi is writing it in Franklin, I think this is what he is going for!

**Comment by lassepe** [comment]
Here is another potential use case for this feature:

Over at ParticleFilters.jl we would like to use Pluto as an "executable documentation" for our repo. Currently we are using Jupyter notbooks for this which has the benefit that users can view the notebook directly in the browser (of course only the static, non-interactive version) without the need to download or run anything.

Of course a 1-click deploy to project binder would solve this issue, however, for our use case it would be totally sufficient to just programmatically export the notebook to static HTML.
Ideally, I am envisioning to export the notebook to HTML automatically through the CI job that also builds the documentation (i.e. as part of docs/make.jl).

**Comment by pankgeorg** [comment]
Why don't we do this with a headless chromium browser like the tests do?

**Comment by fonsp** [comment]
We'll build something equivalent to HTML export into pluto soonish

**Comment by zsunberg** [comment]
Would be great to have this in the next two weeks for use in a class that I am teaching in Julia! Also @mossr could probably benefit for his course materials: https://github.com/sisl/AA120Q

**Comment by ttsugriy** [comment]
@VarLad github action for deploying Pluto notebooks would be awesome. Do you know if it's a thing now?

**Comment by fonsp** [comment]
Check out https://github.com/JuliaPluto/static-export-template/ , which uses https://github.com/JuliaPluto/PlutoSliderServer.jl to generate HTML files without a browser :)
